#include <psptypes.h>
typedef unsigned int uint;
#include <pspsdk.h>

//#include <as_reg_compat.h>
//#include <pspasfparser.h> //not included in devkitPSP r16...
#include <pspatrac3.h>
#include <pspaudio.h>
#include <pspaudio_kernel.h>
#include <pspaudiocodec.h>
#include <pspaudiolib.h>
#include <pspaudiorouting.h>
#include <pspchnnlsv.h>
#include <pspctrl.h>
#include <pspctrl_kernel.h>
#include <pspdebug.h>
#include <pspdebugkb.h>
#include <pspdisplay.h>
#include <pspdisplay_kernel.h>
#include <pspexception.h>
#include <pspfpu.h>
#include <pspge.h>
#include <pspgu.h>
#include <pspgum.h>
#include <psphprm.h>
#include <psphttp.h>
#include <pspidstorage.h>
#include <pspimpose_driver.h>
#include <pspinit.h>
#include <pspintrman.h>
#include <pspintrman_kernel.h>
#include <pspiofilemgr.h>
#include <pspiofilemgr_dirent.h>
#include <pspiofilemgr_fcntl.h>
#include <pspiofilemgr_kernel.h>
#include <pspiofilemgr_stat.h>
#include <pspjpeg.h>
#include <pspkdebug.h>
#include <pspkernel.h>
#include <pspkerneltypes.h>
#include <pspkerror.h>
#include <psploadcore.h>
#include <psploadexec.h>
#include <psploadexec_kernel.h>
#include <pspmoduleexport.h>
#include <pspmoduleinfo.h>
#include <pspmodulemgr.h>
#include <pspmodulemgr_kernel.h>
#include <pspmp3.h>
#include <pspmpeg.h>
#include <pspmpegbase.h>
#include <pspmscm.h>
#include <pspnand_driver.h>
#include <pspnet.h>
#include <pspnet_adhoc.h>
#include <pspnet_adhocctl.h>
#include <pspnet_adhocmatching.h>
#include <pspnet_apctl.h>
#include <pspnet_inet.h>
#include <pspnet_resolver.h>
#include <pspopenpsid.h>
#include <psppower.h>
#include <pspprof.h>
#include <pspreg.h>
#include <psprtc.h>
#include <pspsircs.h>
#include <pspssl.h>
#include <pspstdio.h>
#include <pspstdio_kernel.h>
#include <pspsuspend.h>
#include <pspsysclib.h>
#include <pspsyscon.h>
#include <pspsysevent.h>
#include <pspsysmem.h>
#include <pspsysmem_kernel.h>
#include <pspsysreg.h>
#include <pspsystimer.h>
#include <pspthreadman.h>
#include <pspthreadman_kernel.h>
#include <pspumd.h>
#include <pspusb.h>
#include <pspusbacc.h>
#include <pspusbbus.h>
#include <pspusbcam.h>
#include <pspusbstor.h>
#include <pspuser.h>
#include <psputility.h>
#include <psputility_avmodules.h>
#include <psputility_gamesharing.h>
#include <psputility_htmlviewer.h>
#include <psputility_modules.h>
#include <psputility_msgdialog.h>
#include <psputility_netconf.h>
#include <psputility_netmodules.h>
#include <psputility_netparam.h>
#include <psputility_osk.h>
#include <psputility_savedata.h>
#include <psputility_sysparam.h>
#include <psputility_usbmodules.h>
#include <psputils.h>
#include <psputilsforkernel.h>
#include <pspvfpu.h>
#include <pspvideocodec.h>
#include <pspwlan.h>
